import type { Mentor, Tier, Topic } from './types';

// --- Tiers: the ladder Maya described. Cheap early-stage -> premium operators. ---
export const TIERS: Tier[] = [
  {
    id: 'rise',
    label: 'Rise',
    emoji: '🌱',
    blurb: 'Just starting to build. Cheap, peer-level guidance from people one step ahead of you.',
    priceFrom: 9,
    priceTo: 29,
    accent: '#34d399',
  },
  {
    id: 'build',
    label: 'Build',
    emoji: '🛠️',
    blurb: 'Shipping real products and finding traction. Operators who have done it recently and often.',
    priceFrom: 49,
    priceTo: 149,
    accent: '#22d3ee',
  },
  {
    id: 'scale',
    label: 'Scale',
    emoji: '📡',
    blurb: 'Established founders and community leaders. Premium rates for high-signal, hard-won playbooks.',
    priceFrom: 199,
    priceTo: 499,
    accent: '#f472b6',
  },
];

// --- Topics: the thing you actually need help with. ---
export const TOPICS: Topic[] = [
  { id: 'ai', label: 'AI', emoji: '🤖' },
  { id: 'growth', label: 'Growth', emoji: '📈' },
  { id: 'marketing', label: 'Marketing', emoji: '📣' },
  { id: 'product', label: 'Product', emoji: '🧩' },
  { id: 'no-code', label: 'No-Code', emoji: '⚡' },
  { id: 'design', label: 'Design', emoji: '🎨' },
  { id: 'community', label: 'Community', emoji: '🤝' },
];

// --- Real seed mentors (reused from the CreatorPlaybooks dataset). ---
// tier derived from category: indie-hackers -> rise, netlify-shippers -> build, big-players -> scale.
export const MENTORS: Mentor[] = [
  {
    id: 'maya',
    name: 'Maya',
    handle: '@buildwithmaya',
    xHandle: 'buildwithmaya',
    avatar: '/mentors/maya/avatar.jpg',
    bio: 'Just me, my laptop, and ideas. 9-to-5 side builder sharing lessons to help you build faster. Founder of IdeaPanda + Newbie Marketer.',
    followers: 1774,
    tier: 'rise',
    topics: ['marketing', 'growth', 'product', 'no-code'],
    rate: 12,
    rateNote: 'per 30-min call',
    strengths: ['Distribution & newsletters', 'Building in public', 'Founder lesson synthesis'],
  },
  {
    id: 'rasaljaya',
    name: 'Rasal Jayasinghe',
    handle: '@rasaljaya',
    xHandle: 'rasaljaya',
    avatar: '/mentors/rasaljaya/avatar.jpg',
    bio: "Hosting Sri Lanka's #1 Tech Podcast, TechTalk 360. Cursor Ambassador & Regional Lead South Asia. ElevenLabs Ambassador.",
    followers: 500,
    tier: 'rise',
    topics: ['community', 'ai', 'growth'],
    rate: 15,
    rateNote: 'per 30-min call',
    strengths: ['Local ecosystem building', 'Ambassador programs', 'Podcast authority'],
  },
  {
    id: 'conormartin_',
    name: 'Conor Martin',
    handle: '@conormartinai',
    xHandle: 'conormartin_',
    avatar: '/mentors/conormartin_/avatar.jpg',
    bio: 'Growth Marketer. Millions of views on YouTube and through SEO. Open to full-time roles and consulting.',
    followers: 568,
    tier: 'rise',
    topics: ['growth', 'marketing', 'no-code'],
    rate: 18,
    rateNote: 'per 30-min call',
    strengths: ['YouTube SEO', 'Parasite SEO', 'AI video workflows'],
  },
  {
    id: 'phanindra_ai',
    name: 'Phanindra Reddy',
    handle: '@phanindra_ai',
    xHandle: 'phanindra_ai',
    avatar: '/mentors/phanindra_ai/avatar.jpg',
    bio: 'Building the best AI OS for founders. Daily building-in-public logs with extreme velocity.',
    followers: 1966,
    tier: 'rise',
    topics: ['ai', 'product', 'no-code'],
    rate: 19,
    rateNote: 'per 30-min call',
    strengths: ['AI product velocity', 'Founder outreach', 'Day-N build logs'],
  },
  {
    id: 'nealfrazier',
    name: 'Neal Frazier',
    handle: '@NealFrazierTech',
    xHandle: 'NealFrazierTech',
    avatar: '/mentors/nealfrazier/avatar.jpg',
    bio: 'Creative Technologist. Certified Netlify Partner. Ships static, API-driven creator labs and clear offers.',
    followers: 116,
    tier: 'build',
    topics: ['product', 'marketing', 'no-code'],
    rate: 59,
    rateNote: 'per 45-min call',
    strengths: ['Static/Netlify architecture', 'Booking funnels', 'Launch storytelling'],
  },
  {
    id: 'jaibhagat',
    name: 'Jai Bhagat',
    handle: '@ChaiWithJai',
    xHandle: 'ChaiWithJai',
    avatar: '/mentors/jaibhagat/avatar.jpg',
    bio: 'Product Engineer. Breathwork Facilitator. ex @HashiCorp @Webflow. Runs Claude Code workshops + Dogged Pursuits.',
    followers: 901,
    tier: 'build',
    topics: ['product', 'ai', 'community'],
    rate: 65,
    rateNote: 'per 45-min call',
    strengths: ['AI-assisted engineering', 'Personal branding', 'Live workshops'],
  },
  {
    id: 'gerrit',
    name: 'Gerrit Halfmann',
    handle: '@halfmage',
    xHandle: 'halfmage',
    avatar: '/mentors/gerrit/avatar.jpg',
    bio: 'Solo dev shipping small software with big dreams: Pixelarticons, Majesticons, QR Code Banana.',
    followers: 1114,
    tier: 'build',
    topics: ['product', 'design', 'no-code'],
    rate: 69,
    rateNote: 'per 45-min call',
    strengths: ['Solo dev portfolio', 'Premium icon libraries', 'Public maturation'],
  },
  {
    id: 'maddiedreese',
    name: 'Maddie D. Reese',
    handle: '@maddiedreese',
    xHandle: 'maddiedreese',
    avatar: '/mentors/maddiedreese/avatar.jpg',
    bio: 'Learning! I don’t write code (but you probably won’t believe me). 50+ past projects and weird AI evals.',
    followers: 5006,
    tier: 'build',
    topics: ['ai', 'no-code', 'product'],
    rate: 79,
    rateNote: 'per 45-min call',
    strengths: ['Weird AI experiments', 'Non-traditional building', 'Playful benchmarks'],
  },
  {
    id: 'clarklab',
    name: 'Clark Wimberly',
    handle: '@clarklab',
    xHandle: 'clarklab',
    avatar: '/mentors/clarklab/avatar.jpg',
    bio: 'I try to make things that are awesome. One half of Superfun. Design engineer. BBQ, games, AI wonk.',
    followers: 3718,
    tier: 'build',
    topics: ['design', 'product', 'ai'],
    rate: 89,
    rateNote: 'per 45-min call',
    strengths: ['Game prototyping', 'Design engineering', 'Playful UI/UX'],
  },
  {
    id: 'ash_wesley_',
    name: 'Ash 🔊',
    handle: '@AshAmplifies',
    xHandle: 'AshAmplifies',
    avatar: '/mentors/ash_wesley_/avatar.jpg',
    bio: 'AI Shipper building in public. Product builder, internet curator, meetup co-founder (AI Shippers Community).',
    followers: 3131,
    tier: 'build',
    topics: ['ai', 'community', 'product'],
    rate: 95,
    rateNote: 'per 45-min call',
    strengths: ['Tiny shipping series', 'Community amplification', 'Creative discovery'],
  },
  {
    id: 'ayushtweetshere',
    name: 'Ayush 🙏',
    handle: '@ayushtweetshere',
    xHandle: 'ayushtweetshere',
    avatar: '/mentors/ayushtweetshere/avatar.jpg',
    bio: 'Father, husband, son, friend. Independent entrepreneur. OutlierKit, Voibe, Superframeworks. Transparent MRR.',
    followers: 12100,
    tier: 'build',
    topics: ['product', 'growth', 'marketing'],
    rate: 129,
    rateNote: 'per 45-min call',
    strengths: ['Bootstrapped MRR', 'Side-project sales', 'Pricing experiments'],
  },
  {
    id: 'monroe_carol',
    name: 'Carol Monroe',
    handle: '@CarolMonroe',
    xHandle: 'CarolMonroe',
    avatar: '/mentors/monroe_carol/avatar.jpg',
    bio: 'AI Strategist & Creative Builder. Frontier AI creative work + humanitarian tech for impact.',
    followers: 7771,
    tier: 'build',
    topics: ['ai', 'marketing', 'community'],
    rate: 139,
    rateNote: 'per 45-min call',
    strengths: ['AI strategy frameworks', 'Builder mobilization', 'Creative building'],
  },
  {
    id: 'lynnzeng',
    name: 'Lynn Zeng',
    handle: '@zeng_wt',
    xHandle: 'zeng_wt',
    avatar: '/mentors/lynnzeng/avatar.png',
    bio: 'AI Creative, Film Maker, AI Artist. PicAisso, NewMom Help. Generous with full prompts + workflows.',
    followers: 6568,
    tier: 'scale',
    topics: ['ai', 'design', 'marketing'],
    rate: 249,
    rateNote: 'per 60-min call',
    strengths: ['AI film & motion', 'Prompt workflows', 'High-taste visuals'],
  },
  {
    id: 'kp',
    name: 'KP',
    handle: '@thisiskp_',
    xHandle: 'thisiskp_',
    avatar: '/mentors/kp/avatar.jpg',
    bio: 'The "Build In Public" Guy. Head of Community at @Netlify. Vibe Coder. Prev: @PaddleHQ @joinODF.',
    followers: 70600,
    tier: 'scale',
    topics: ['community', 'growth', 'ai'],
    rate: 399,
    rateNote: 'per 60-min call',
    strengths: ['Community amplification', 'Build-in-public systems', 'Vibe coding'],
  },
];
