import type { Category, SessionType, Tier, Expert } from './types';

// --- The three narrow wedges we launch with. ---
export const CATEGORIES: Category[] = [
  {
    id: 'launch',
    label: 'Launch & distribution',
    emoji: '🚀',
    blurb: 'Get it out and in front of the right people. Launch plans, first-users, growth.',
    accent: '#22d3ee',
  },
  {
    id: 'positioning',
    label: 'Landing page / positioning',
    emoji: '🎯',
    blurb: 'Make the page and the offer land. Teardowns, offer reviews, clarity.',
    accent: '#f472b6',
  },
  {
    id: 'content',
    label: 'Founder content / X growth',
    emoji: '✍️',
    blurb: 'Build an audience that compounds. X strategy, newsletters, founder voice.',
    accent: '#34d399',
  },
];

// --- Outcome-based session products. Each is a product, not a random call. ---
export const SESSIONS: SessionType[] = [
  { id: 'landing-teardown', label: 'Landing page teardown', emoji: '🖼️', category: 'positioning',
    blurb: 'A blunt, specific teardown of your hero, proof, and CTA — with 5 fixes you can ship today.' },
  { id: 'idea-validation', label: 'SaaS idea validation', emoji: '🧪', category: 'launch',
    blurb: 'A no-BS gut-check on whether the problem is real, who pays, and what to build first.' },
  { id: 'launch-plan', label: 'Launch plan', emoji: '🗓️', category: 'launch',
    blurb: 'A concrete launch sequence — channels, timeline, and the one thing to nail first.' },
  { id: 'x-strategy', label: 'X / content strategy', emoji: '🐦', category: 'content',
    blurb: 'A founder-content system: angles, cadence, and the posts that actually compound.' },
  { id: 'offer-review', label: 'Offer / positioning review', emoji: '💡', category: 'positioning',
    blurb: 'Sharpen what you sell and to whom — pricing, packaging, and the one-line pitch.' },
  { id: 'first-users', label: 'First-users strategy', emoji: '🌱', category: 'launch',
    blurb: 'Where your first 10–100 users actually come from, and the exact outreach to get them.' },
  { id: 'growth-audit', label: 'Growth audit', emoji: '📈', category: 'launch',
    blurb: 'A teardown of your funnel with the 2–3 growth levers worth pulling first.' },
  { id: 'newsletter', label: 'Newsletter growth call', emoji: '📰', category: 'content',
    blurb: 'Hooks, cadence, and a plan to turn a small list into your best distribution channel.' },
];

// --- Tiers (pricing bands). Manual marketplace pricing to start. ---
export const TIERS: Tier[] = [
  { id: 'micro', label: 'Rising builders', emoji: '🌱', priceFrom: 49, priceTo: 99, accent: '#34d399' },
  { id: 'proven', label: 'Proven operators', emoji: '🛠️', priceFrom: 99, priceTo: 199, accent: '#22d3ee' },
  { id: 'status', label: 'High-status', emoji: '📡', priceFrom: 200, priceTo: null, accent: '#f472b6' },
];

// --- Vetted experts. Real builders/operators with proof of work — no guru energy. ---
// Seed set drawn from the CreatorPlaybooks mentor network; re-cast as tactical experts.
export const EXPERTS: Expert[] = [
  {
    id: 'maya',
    name: 'Maya',
    handle: '@buildwithmaya',
    xHandle: 'buildwithmaya',
    avatar: '/mentors/maya/avatar.jpg',
    bio: 'Just me, my laptop, and ideas. 9-to-5 side builder sharing lessons to help you build faster. Founder of IdeaPanda + Newbie Marketer.',
    followers: 1774,
    tier: 'micro',
    categories: ['content', 'positioning'],
    sessions: ['newsletter', 'x-strategy', 'landing-teardown'],
    rate: 89,
    rateNote: 'per person · 30-min session',
    proof: ['Founder of IdeaPanda + Newbie Marketer', '1.7K builders follow her build-in-public lessons', 'Ships a live newsletter on distribution'],
    outcomes: ['A rewritten newsletter hook + send-cadence plan', '3 ready-to-post founder-thread angles', 'A landing-page clarity pass on your hero + CTA'],
    canHelpWith: ['My newsletter is flat', 'I post but nothing lands', 'My landing page is confusing'],
  },
  {
    id: 'rasaljaya',
    name: 'Rasal Jayasinghe',
    handle: '@rasaljaya',
    xHandle: 'rasaljaya',
    avatar: '/mentors/rasaljaya/avatar.jpg',
    bio: "Hosting Sri Lanka's #1 Tech Podcast, TechTalk 360. Cursor Ambassador & Regional Lead South Asia. ElevenLabs Ambassador.",
    followers: 500,
    tier: 'micro',
    categories: ['content', 'launch'],
    sessions: ['x-strategy', 'launch-plan', 'first-users'],
    rate: 89,
    rateNote: 'per person · 30-min session',
    proof: ["Hosts Sri Lanka's #1 tech podcast (TechTalk 360)", 'Cursor + ElevenLabs Ambassador, South Asia', 'Builds local dev communities from scratch'],
    outcomes: ['An ambassador / community launch playbook', 'A 30-day founder-content calendar', 'A first-10-users outreach template'],
    canHelpWith: ['How do I launch to a community', 'No audience to launch to', 'Content that builds a following'],
  },
  {
    id: 'conormartin_',
    name: 'Conor Martin',
    handle: '@conormartinai',
    xHandle: 'conormartin_',
    avatar: '/mentors/conormartin_/avatar.jpg',
    bio: 'Growth Marketer. Millions of views on YouTube and through SEO. Open to full-time roles and consulting.',
    followers: 568,
    tier: 'status',
    categories: ['launch', 'content'],
    sessions: ['growth-audit', 'x-strategy', 'launch-plan'],
    rate: 299,
    rateNote: 'per person · 30-min session',
    proof: ['Millions of YouTube views via SEO', 'Parasite + programmatic SEO operator', 'Runs paid + organic growth tests'],
    outcomes: ['An SEO / content gap audit with quick wins', 'A founder YouTube or X angle', 'A launch-distribution checklist'],
    canHelpWith: ['Growth is stalled', 'SEO or YouTube for a founder', 'Where to find distribution'],
  },
  {
    id: 'phanindra_ai',
    name: 'Phanindra Reddy',
    handle: '@phanindra_ai',
    xHandle: 'phanindra_ai',
    avatar: '/mentors/phanindra_ai/avatar.jpg',
    bio: 'Building the best AI OS for founders. Daily building-in-public logs with extreme velocity.',
    followers: 1966,
    tier: 'micro',
    categories: ['launch', 'positioning'],
    sessions: ['idea-validation', 'landing-teardown', 'first-users'],
    rate: 89,
    rateNote: 'per person · 30-min session',
    proof: ['Building an AI OS for founders in public', 'Daily day-N build logs', 'Extreme shipping velocity, honest lessons'],
    outcomes: ['A blunt idea-validation scorecard', 'A landing-page rewrite (hero + proof)', 'A "first users" DM / outreach script'],
    canHelpWith: ['Is this idea worth building', 'My page does not convert', 'How to get the first users'],
  },
  {
    id: 'nealfrazier',
    name: 'Neal Frazier',
    handle: '@NealFrazierTech',
    xHandle: 'NealFrazierTech',
    avatar: '/mentors/nealfrazier/avatar.jpg',
    bio: 'Creative Technologist. Certified Netlify Partner. Ships static, API-driven creator labs and clear offers.',
    followers: 116,
    tier: 'proven',
    categories: ['positioning', 'launch'],
    sessions: ['landing-teardown', 'offer-review', 'launch-plan'],
    rate: 89,
    rateNote: 'per person · 30-min session',
    proof: ['Certified Netlify Partner', 'Ships static, API-driven creator labs', 'Builds clear booking + offer funnels'],
    outcomes: ['A landing-page teardown with 5 fixes', 'A rewritten offer + pricing ladder', 'A launch-story angle that converts'],
    canHelpWith: ['My landing page underperforms', 'My offer is muddy', 'How to tell the launch story'],
  },
  {
    id: 'jaibhagat',
    name: 'Jai Bhagat',
    handle: '@ChaiWithJai',
    xHandle: 'ChaiWithJai',
    avatar: '/mentors/jaibhagat/avatar.jpg',
    bio: 'Product Engineer. Breathwork Facilitator. ex @HashiCorp @Webflow. Runs Claude Code workshops + Dogged Pursuits.',
    followers: 901,
    tier: 'status',
    categories: ['positioning', 'launch'],
    sessions: ['landing-teardown', 'idea-validation', 'x-strategy'],
    rate: 259,
    rateNote: 'per person · 30-min session',
    proof: ['ex @HashiCorp @Webflow product engineer', 'Runs Claude Code workshops', 'Personal-branding + live-workshop builder'],
    outcomes: ['A product / positioning clarity session', 'A landing-page teardown for technical products', 'A personal-brand content plan'],
    canHelpWith: ['Technical product positioning', 'Landing page for a dev tool', 'Building a personal brand'],
  },
  {
    id: 'gerrit',
    name: 'Gerrit Halfmann',
    handle: '@halfmage',
    xHandle: 'halfmage',
    avatar: '/mentors/gerrit/avatar.jpg',
    bio: 'Solo dev shipping small software with big dreams: Pixelarticons, Majesticons, QR Code Banana.',
    followers: 1114,
    tier: 'proven',
    categories: ['positioning', 'launch'],
    sessions: ['landing-teardown', 'offer-review', 'first-users'],
    rate: 89,
    rateNote: 'per person · 30-min session',
    proof: ['Solo dev behind Pixelarticons + Majesticons', 'QR Code Banana maker', 'Publicly documents his solo journey'],
    outcomes: ['A landing-page conversion pass', 'A pricing / packaging review', 'A solo-dev "first users" plan'],
    canHelpWith: ['Solo dev, no distribution', 'Pricing my side project', 'Page does not convert'],
  },
  {
    id: 'maddiedreese',
    name: 'Maddie D. Reese',
    handle: '@maddiedreese',
    xHandle: 'maddiedreese',
    avatar: '/mentors/maddiedreese/avatar.jpg',
    bio: "Learning! I don't write code (but you probably won't believe me). 50+ past projects and weird AI evals.",
    followers: 5006,
    tier: 'proven',
    categories: ['launch', 'content'],
    sessions: ['idea-validation', 'x-strategy', 'growth-audit'],
    rate: 89,
    rateNote: 'per person · 30-min session',
    proof: ['50+ shipped projects', 'Known for weird, high-signal AI evals', '5K+ following her experiments'],
    outcomes: ['A no-BS idea-validation reality check', 'A distinctive founder-content angle', 'A growth experiment you can actually run'],
    canHelpWith: ['Is this idea real', 'Standing out with content', 'Growth feels random'],
  },
  {
    id: 'clarklab',
    name: 'Clark Wimberly',
    handle: '@clarklab',
    xHandle: 'clarklab',
    avatar: '/mentors/clarklab/avatar.jpg',
    bio: 'I try to make things that are awesome. One half of Superfun. Design engineer. BBQ, games, AI wonk.',
    followers: 3718,
    tier: 'proven',
    categories: ['positioning', 'launch'],
    sessions: ['landing-teardown', 'offer-review', 'launch-plan'],
    rate: 89,
    rateNote: 'per person · 30-min session',
    proof: ['Design engineer, one half of Superfun', 'Ships playful game prototypes', 'AI-wonk with a high-taste eye'],
    outcomes: ['A landing-page UX / visual teardown', 'An offer + pricing clarity pass', 'A delightful launch-page concept'],
    canHelpWith: ['My page looks off', 'Offer is unclear', 'Make the launch memorable'],
  },
  {
    id: 'ash_wesley_',
    name: 'Ash 🔊',
    handle: '@AshAmplifies',
    xHandle: 'AshAmplifies',
    avatar: '/mentors/ash_wesley_/avatar.jpg',
    bio: 'AI Shipper building in public. Product builder, internet curator, meetup co-founder (AI Shippers Community).',
    followers: 3131,
    tier: 'status',
    categories: ['launch', 'content'],
    sessions: ['first-users', 'x-strategy', 'launch-plan'],
    rate: 279,
    rateNote: 'per person · 30-min session',
    proof: ['Co-founded AI Shippers Community meetup', 'Daily AI-shipping in public', 'Internet curator + product builder'],
    outcomes: ['A first-users community playbook', 'A founder X growth plan', 'A launch-amplification checklist'],
    canHelpWith: ['Find my first users', 'Grow on X as a founder', 'Plan a launch that spreads'],
  },
  {
    id: 'ayushtweetshere',
    name: 'Ayush 🙏',
    handle: '@ayushtweetshere',
    xHandle: 'ayushtweetshere',
    avatar: '/mentors/ayushtweetshere/avatar.jpg',
    bio: 'Father, husband, son, friend. Independent entrepreneur. OutlierKit, Voibe, Superframeworks. Transparent MRR.',
    followers: 12100,
    tier: 'proven',
    categories: ['positioning', 'launch'],
    sessions: ['offer-review', 'idea-validation', 'growth-audit'],
    rate: 89,
    rateNote: 'per person · 30-min session',
    proof: ['Transparent bootstrapped MRR (OutlierKit, Voibe)', 'Side-project sales operator', '12K followers on founder X'],
    outcomes: ['A pricing + offer teardown', 'An idea-validation gut-check', 'A growth audit with revenue levers'],
    canHelpWith: ['Pricing feels wrong', 'Is this idea worth it', 'Growth has stalled'],
  },
  {
    id: 'monroe_carol',
    name: 'Carol Monroe',
    handle: '@CarolMonroe',
    xHandle: 'CarolMonroe',
    avatar: '/mentors/monroe_carol/avatar.jpg',
    bio: 'AI Strategist & Creative Builder. Frontier AI creative work + humanitarian tech for impact.',
    followers: 7771,
    tier: 'proven',
    categories: ['launch', 'content'],
    sessions: ['launch-plan', 'x-strategy', 'growth-audit'],
    rate: 89,
    rateNote: 'per person · 30-min session',
    proof: ['AI strategist + creative builder', '7.7K followers on founder content', 'Frontier AI creative + impact work'],
    outcomes: ['A launch plan you can execute this week', 'A founder content system', 'A growth audit with focus areas'],
    canHelpWith: ['Plan a real launch', 'Build a content system', 'Where to focus growth'],
  },
  {
    id: 'lynnzeng',
    name: 'Lynn Zeng',
    handle: '@zeng_wt',
    xHandle: 'zeng_wt',
    avatar: '/mentors/lynnzeng/avatar.png',
    bio: 'AI Creative, Film Maker, AI Artist. PicAisso, NewMom Help. Generous with full prompts + workflows.',
    followers: 6568,
    tier: 'status',
    categories: ['positioning', 'content'],
    sessions: ['landing-teardown', 'x-strategy', 'offer-review'],
    rate: 249,
    rateNote: 'per person · 30-min session',
    proof: ['AI film + motion artist (PicAisso, NewMom Help)', 'Generous with full prompts / workflows', 'High-taste visual brand'],
    outcomes: ['A landing-page + visual-brand teardown', 'A founder-content angle with taste', 'An offer / packaging review'],
    canHelpWith: ['Page + brand feel off', 'Content with real taste', 'Offer / packaging review'],
  },
  {
    id: 'kp',
    name: 'KP',
    handle: '@thisiskp_',
    xHandle: 'thisiskp_',
    avatar: '/mentors/kp/avatar.jpg',
    bio: 'The "Build In Public" Guy. Head of Community at @Netlify. Vibe Coder. Prev: @PaddleHQ @joinODF.',
    followers: 70600,
    tier: 'status',
    categories: ['content', 'launch'],
    sessions: ['x-strategy', 'launch-plan', 'first-users'],
    rate: 449,
    rateNote: 'per person · 30-min session',
    proof: ['Head of Community @Netlify', '"Build In Public" guy, 70K followers', 'Vibe coder, prev @PaddleHQ @joinODF'],
    outcomes: ['A build-in-public content system', 'A launch-distribution plan', 'A first-users community strategy'],
    canHelpWith: ['Build an in-public audience', 'Plan a launch that spreads', 'Get the first users'],
  },
];
